/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_processwarp_android_Router */

#ifndef _Included_org_processwarp_android_Router
#define _Included_org_processwarp_android_Router
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_processwarp_android_Router
 * Method:    schedulerInitialize
 * Signature: (Lorg/processwarp/android/Router;)V
 */
JNIEXPORT void JNICALL Java_org_processwarp_android_Router_schedulerInitialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_processwarp_android_Router
 * Method:    schedulerGetDstNid
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_processwarp_android_Router_schedulerGetDstNid
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_processwarp_android_Router
 * Method:    schedulerRecvCommand
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_processwarp_android_Router_schedulerRecvCommand
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     org_processwarp_android_Router
 * Method:    schedulerSetNodeInformation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_processwarp_android_Router_schedulerSetNodeInformation
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_processwarp_android_Router_Delegate */

#ifndef _Included_org_processwarp_android_Router_Delegate
#define _Included_org_processwarp_android_Router_Delegate
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
