language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6

    packages:
      - g++-4.8
      - gcc-4.8
      - clang-3.6
      - clang-format-3.6
      - libboost-system1.55-dev
      - libboost-date-time1.55-dev
      - libboost-random1.55-dev
      - libgtest-dev

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -yqq
  - export CC=clang-3.6
  - export CXX=clang++-3.6
  # install cpplint
  - curl https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py > /tmp/cpplint.py
  - sudo mv /tmp/cpplint.py /usr/local/bin/
  - sudo chmod 755 /usr/local/bin/cpplint.py
  # install gtest
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv /usr/src/gtest/libgtest* /usr/local/lib/
  # download file
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p tmp
  - curl https://cmake.org/files/v3.5/cmake-3.5.0.tar.gz > tmp/cmake-3.5.0.tar.gz
  # finish before
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR

install:
  - script/build.sh
  - local/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_TEST=ON .
  - make
  - make test
  - make cpplint
  - local/bin/cmake -DCMAKE_BUILD_TYPE=Release -DWITH_TEST=ON .
  - make
  - make test
  
script:
  - ls -l bin
  - export PATH=$TRAVIS_BUILD_DIR/local/bin:$PATH
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/local/lib:$LD_LIBRARY_PATH
  - bin/processwarp --help
